name       : python3-pyudev
version    : 0.22.0
release    : 5
source     :
    - https://pypi.io/packages/source/p/pyudev/pyudev-0.22.0.tar.gz : 69bb1beb7ac52855b6d1b9fe909eefb0017f38d917cba9939602c6880035b276
license    : LGPL-2.1-or-later
component  : programming.python
summary    : pyudev is a LGPL licensed, pure Python binding for libudev
description: |
    pyudev is a LGPL licensed, pure Python binding for libudev
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
