name       : python3-pyudev
version    : 0.21.0
release    : 1
source     :
    - https://pypi.python.org/packages/bc/a2/31a07829acea8e70a28c247f43fa5d981229ae0f9edfeddedf52de00709b/pyudev-0.21.0.tar.gz : 094b7a100150114748aaa3b70663485dd360457a709bfaaafe5a977371033f2b
license    : LGPL-2.1
component  : programming.python
summary    : pyudev is a LGPL licensed, pure Python binding for libudev
description: |
   pyudev is a LGPL licensed, pure Python binding for libudev
builddeps  :
    - pkgconfig(python-3.5)
build      : |
    %python3_setup
install    : |
    %python3_install
