name       : python3-pyudev
version    : 0.23.1
release    : 8
source     :
    - https://github.com/pyudev/pyudev/archive/refs/tags/v0.23.1.tar.gz : 258fcd252495e672645e6697678f7cbfef455f317e9a923ae944cf800e14791d
license    : LGPL-2.1-or-later
component  : programming.python
summary    : pyudev is a LGPL licensed, pure Python binding for libudev
description: |
    pyudev is a LGPL licensed, pure Python binding for libudev
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
